version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: "pg,sched"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
# Для публикации в Rabbit добавь брокер и профиль 'amqp' (см. Step 7)
