version: "3.9"

services:
  db:
    image: postgres:16
    container_name: step5-postgres
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: step5-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: "pg"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
    command: ["sh","-c","java -Dspring.profiles.active=pg $JAVA_OPTS -jar /app/app.jar"]
    ports:
      - "8080:8080"
    restart: unless-stopped
